name: recipe_haven
description: "Cooking Recipes."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  bloc_test: ^10.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  logging: ^1.3.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2 
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  injectable_generator: ^2.7.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/companies_icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
