// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnSppDVAJxY-FMCNqfpPHqkpMBCw_8eQc',
    appId: '1:807455539979:web:399ad4cfab1937f88b180e',
    messagingSenderId: '807455539979',
    projectId: 'recipe-haven-c8169',
    authDomain: 'recipe-haven-c8169.firebaseapp.com',
    storageBucket: 'recipe-haven-c8169.firebasestorage.app',
    measurementId: 'G-2NFBHNT6NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPpzoOpbZDyOVLd_LQ1Ry-XGsCX6nSghg',
    appId: '1:807455539979:android:74e030493f7e96a78b180e',
    messagingSenderId: '807455539979',
    projectId: 'recipe-haven-c8169',
    storageBucket: 'recipe-haven-c8169.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaYZSOxEq-jr7LMXlbEym8TV-PFdP7F8',
    appId: '1:807455539979:ios:24f84aa331c1d5638b180e',
    messagingSenderId: '807455539979',
    projectId: 'recipe-haven-c8169',
    storageBucket: 'recipe-haven-c8169.firebasestorage.app',
    iosBundleId: 'com.example.recipeHaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqaYZSOxEq-jr7LMXlbEym8TV-PFdP7F8',
    appId: '1:807455539979:ios:24f84aa331c1d5638b180e',
    messagingSenderId: '807455539979',
    projectId: 'recipe-haven-c8169',
    storageBucket: 'recipe-haven-c8169.firebasestorage.app',
    iosBundleId: 'com.example.recipeHaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnSppDVAJxY-FMCNqfpPHqkpMBCw_8eQc',
    appId: '1:807455539979:web:4f9b0673be3be8dd8b180e',
    messagingSenderId: '807455539979',
    projectId: 'recipe-haven-c8169',
    authDomain: 'recipe-haven-c8169.firebaseapp.com',
    storageBucket: 'recipe-haven-c8169.firebasestorage.app',
    measurementId: 'G-F6Z40DHD6X',
  );

}